package keepcalm.mods.forgechat;

import static keepcalm.mods.forgecore.ForgeModsVersioning.DISPLAY_VER;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import net.minecraft.client.Minecraft;
import net.minecraft.server.MinecraftServer;
import net.minecraft.src.CrashReport;
import net.minecraft.src.FontRenderer;
import net.minecraft.src.GuiErrorScreen;
import net.minecraft.src.MinecraftException;


import cpw.mods.fml.client.CustomModLoadingErrorDisplayException;
import cpw.mods.fml.client.GuiCustomModLoadingErrorScreen;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Side;
import cpw.mods.fml.common.Mod.Metadata;
import cpw.mods.fml.common.event.FMLServerStoppingEvent;
import cpw.mods.fml.common.versioning.ArtifactVersion;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.server.FMLServerHandler;
import cpw.mods.fml.common.ModContainer;

@Mod(modid="ForgeChat_Dummy", name="ForgeChat", version="1.4.2-0")
public class ForgeChatContainer {
	
	@Metadata("ForgeChat_Dummy")
	public static ModMetadata myMeta = new ModMetadata();
	
	private static List<ModContainer> children = new ArrayList<ModContainer>();
	
	public static void registerChildMod(ModContainer mc) {
		children.add(mc);
	}
	
	
	public ForgeChatContainer() {
		Class clazz;
		try {
			clazz = getClass().getClassLoader().loadClass("keepcalm.mods.forgecore.ForgeCoreModContainer");
			
		} catch (ClassNotFoundException e) {
			CrashReport cr = new CrashReport("You need to install ForgeCore!", e);
			if (Side.CLIENT.isClient()) {
				Minecraft.getMinecraft().displayCrashReport(cr);
			}
			else {
				FMLServerHandler.instance().haltGame("You need to install ForgeCore!", e);
			}
		}
		
		myMeta.autogenerated = false;
		myMeta.version = "1.4.2-0";
		myMeta.name = "ForgeChat";
		myMeta.modId = "ForgeChat_Dummy";

		
		
	}

}
